version: "3"

services:

  api:
    container_name: "snippet-service"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      AUTH0_API: ${AUTH0_API}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      PORT: ${PORT}
      PERMIT_PORT: ${PERMIT_PORT}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8082:8082"
    volumes:
      - ./data:/app/data
    depends_on:
      - snippet-db
      - asset

  asset:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: "azurite"
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
      volumes:
        - blob:/workspace

  snippet-db:
    image: postgres:alpine
    container_name: snippet-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

  printscript_service:
    container_name: "printscript_service"
    image: ghcr.io/tps-ingenieria-de-sistemas/printscript-service:0.0.2-snapshot
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8084:8084"

  snippet-permits:
    container_name: "snippet-permits"
    image: ghcr.io/tps-ingenieria-de-sistemas/snippet-permits:latest
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - POSTGRES_DOMAIN=snippet-permits-db
      - POSTGRES_DB=${PERMITS_POSTGRES_DB}
      - POSTGRES_USER=${PERMITS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PERMITS_POSTGRES_PASSWORD}
      - AUTH0_API=${AUTH0_API}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    depends_on:
      - snippet-permits-db

  snippet-permits-db:
    image: postgres:alpine
    container_name: "snippet-permits-db"
    restart: always
    environment:
      - POSTGRES_DB=${PERMITS_POSTGRES_DB}
      - POSTGRES_USER=${PERMITS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PERMITS_POSTGRES_PASSWORD}
      - PGPORT=5433
    ports:
      - '5433:5433'
    volumes:
      - snippet-permits-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${PERMITS_POSTGRES_USER} -d ${PERMITS_POSTGRES_DB}' ]
      interval: 1s
      timeout: 1s
      retries: 15



volumes:
  blob:
    external: false
  snippet-permits-db-data:
  db-data:
