version: "3.9"

services:

  api:
    container_name: "snippets-service"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_DOCKER_SERVICE}:5432/${POSTGRES_DB}?connect_timeout=600
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    depends_on:
      - snippet-db
      - asset

  asset:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: "azurite"
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
      volumes:
        - blob:/workspace

  snippet-db:
    image: postgres:alpine
    container_name: snippet-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  blob:
    external: false
  db-data:
